### ISSUE TITLE
Docker-compose failes on initializing Async-scraper

### ISSUE THREAD

**Issue by jakeroot** [CIRCL/lookyloo#57]
Hi, 

today I wanted to setup a docker container and faced the following issue. All previous 16/19 steps went well. Could someone have a look and advise how to fix it? Thank you. 

Step 17/19 : run nohup pipenv run async_scrape.py
 ---> Running in 0197ffd4a2bc
Loading .env environment variables…
09:06:05 AsyncScraper INFO:Initializing AsyncScraper
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/lookyloo-lb761Agm/lib/python3.6/site-packages/redis/connection.py", line 538, in connect
    sock = self._connect()
  File "/root/.local/share/virtualenvs/lookyloo-lb761Agm/lib/python3.6/site-packages/redis/connection.py", line 861, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/lookyloo-lb761Agm/bin/async_scrape.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root_lookyloo/lookyloo/bin/async_scrape.py", line 36, in <module>
    m = AsyncScraper()
  File "/root_lookyloo/lookyloo/bin/async_scrape.py", line 24, in __init__
    self.lookyloo = Lookyloo(loglevel=loglevel, only_global_lookups=only_global_lookups)
  File "/root_lookyloo/lookyloo/lookyloo/lookyloo.py", line 45, in __init__
    if not self.redis.exists('cache_loaded'):
  File "/root/.local/share/virtualenvs/lookyloo-lb761Agm/lib/python3.6/site-packages/redis/client.py", line 1307, in exists
    return self.execute_command('EXISTS', *names)
  File "/root/.local/share/virtualenvs/lookyloo-lb761Agm/lib/python3.6/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/root/.local/share/virtualenvs/lookyloo-lb761Agm/lib/python3.6/site-packages/redis/connection.py", line 1071, in get_connection
    connection.connect()
  File "/root/.local/share/virtualenvs/lookyloo-lb761Agm/lib/python3.6/site-packages/redis/connection.py", line 543, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /root_lookyloo/lookyloo/cache/cache.sock. No such file or directory.
ERROR: Service 'lookyloo' failed to build: The command '/bin/sh -c nohup pipenv run async_scrape.py' returned a non-zero code: 1

**Comment by Rafiot** [comment]
Hmm looks like redis-server isn't started. Maybe it's not even present on the image...

I don't use the docker image, so I didn't notice that, sorry. I'll fix it asap.

**Comment by dadigi** [comment]
With that change the docker build no gets stuck at that point (due to missing redis):
../../redis/src/redis-server ./cache.conf
./run_redis.sh: line 6: ../../redis/src/redis-server: No such file or directory

**Comment by Rafiot** [comment]
Alright, it is definitely not working and I need to redo the whole docker thing so I don break it every other day.

I'll let you know if/when I figure that out but in the meantime, PR are welcome.

**Comment by Rafiot** [comment]
In theory, the latest commit makes `docker-compose up` working.  Please open an other issue if there are problems.
