### ISSUE TITLE
exception in solve_cf_challenge - can't access web interface in docker-compose setup

### ISSUE THREAD

**Issue by fin** [CIRCL/lookyloo#58]
Hi!

When going to `http://localhost:5100` after running `docker-compose up`, the page does not load and an Exception in `solve_cf_challenge` is printed in console:

```
lookyloo_1  | [2019-12-17 13:10:26,470] ERROR in app: Exception on / [GET]
lookyloo_1  | Traceback (most recent call last):
lookyloo_1  |   File "/root/.local/share/virtualenvs/lookyloo-XyNVP4SX/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
lookyloo_1  |     response = self.full_dispatch_request()
lookyloo_1  |   File "/root/.local/share/virtualenvs/lookyloo-XyNVP4SX/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
lookyloo_1  |     rv = self.handle_user_exception(e)
lookyloo_1  |   File "/root/.local/share/virtualenvs/lookyloo-XyNVP4SX/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
lookyloo_1  |     reraise(exc_type, exc_value, tb)
lookyloo_1  |   File "/root/.local/share/virtualenvs/lookyloo-XyNVP4SX/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
lookyloo_1  |     raise value
lookyloo_1  |   File "/root/.local/share/virtualenvs/lookyloo-XyNVP4SX/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
lookyloo_1  |     rv = self.dispatch_request()
lookyloo_1  |   File "/root/.local/share/virtualenvs/lookyloo-XyNVP4SX/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
lookyloo_1  |     return self.view_functions[rule.endpoint](**req.view_args)
lookyloo_1  |   File "/lookyloo/website/web/__init__.py", line 161, in index
lookyloo_1  |     update_user_agents()
lookyloo_1  |   File "/lookyloo/lookyloo/helpers.py", line 102, in update_user_agents
lookyloo_1  |     r = s.get('https://techblog.willshouse.com/2012/01/03/most-common-user-agents/')
lookyloo_1  |   File "/root/.local/share/virtualenvs/lookyloo-XyNVP4SX/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
lookyloo_1  |     return self.request('GET', url, **kwargs)
lookyloo_1  |   File "/root/.local/share/virtualenvs/lookyloo-XyNVP4SX/lib/python3.6/site-packages/cfscrape/__init__.py", line 128, in request
lookyloo_1  |     resp = self.solve_cf_challenge(resp, **kwargs)
lookyloo_1  |   File "/root/.local/share/virtualenvs/lookyloo-XyNVP4SX/lib/python3.6/site-packages/cfscrape/__init__.py", line 195, in solve_cf_challenge
lookyloo_1  |     redirect_location = urlparse(redirect.headers["Location"])
lookyloo_1  |   File "/root/.local/share/virtualenvs/lookyloo-XyNVP4SX/lib/python3.6/site-packages/requests/structures.py", line 52, in __getitem__
lookyloo_1  |     return self._store[key.lower()][1]
lookyloo_1  | KeyError: 'location'
```

**Comment by Rafiot** [comment]
Yep, I'm pushing a fix as we speak ;)

**Comment by Rafiot** [comment]
Here it is https://github.com/CIRCL/lookyloo/commit/5cfe5306b20738d5db3bce03c1df3a7c45355351

**Comment by Rafiot** [comment]
For the records, this PR will solve it: https://github.com/Anorov/cloudflare-scrape/pull/315

**Comment by fin** [comment]
much obliged 🙏
